services:
  - type: web
    name: NETSOL SUPPORT Chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NETSOL_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
